services:
  api:
    build: .
    container_name: scrapper-api
    ports:
      - '5001:5001'
    # Mount code for live development edits (no reloader is configured by default)
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      # Safe defaults for development
      - DEBUG=true
      - PLAYWRIGHT_HEADLESS=true
      - DATABASE_URL=postgresql+psycopg://postgres:${POSTGRES_DB_PASSWORD}@db:5432/db
    # Increase shared memory to reduce Chromium crashes
    shm_size: '1gb'
    depends_on:
      - db

  scheduler:
    build: .
    container_name: scrapper-scheduler
    command: ['python', 'run_scheduler.py']
    env_file:
      - .env
    environment:
      - DEBUG=false
      - PLAYWRIGHT_HEADLESS=true
      # Cron expression for the sample job (default: hourly)
      - CRON_POPULAR=1 * * * *
    volumes:
      - ./:/app
      - ./artifacts:/app/artifacts
    shm_size: '1gb'

  db:
    image: postgres:17.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: db
      TZ: 'Asia/Manila'
    volumes:
      - postgres15-data:/var/lib/postgresql/data
    shm_size: 1gb
