services:
  api:
    image: scrapper-backend:latest
    container_name: scrapper-api-prod
    ports:
      - '127.0.0.1:5001:5001'
    env_file:
      - .env
    environment:
      - DEBUG=false
      - PLAYWRIGHT_HEADLESS=true
    volumes:
      # Persist scraper artifacts from container to host
      - ./artifacts:/app/artifacts
    # In production we do not mount the source tree
    restart: unless-stopped
    shm_size: '1gb'
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  scheduler:
    image: scrapper-backend:latest
    container_name: scrapper-scheduler-prod
    command: ['python', 'run_scheduler.py']
    env_file:
      - .env
    environment:
      - DEBUG=false
      - PLAYWRIGHT_HEADLESS=true
      # Default: hourly
      - CRON_POPULAR=* 1 * * *
    volumes:
      - ./artifacts:/app/artifacts
    restart: unless-stopped
    shm_size: '1gb'
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
