version: "3.8"

services:
  api:
    build: .
    container_name: scrapper-api
    ports:
      - "5001:5001"
    # Mount code for live development edits (no reloader is configured by default)
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      # Safe defaults for development
      - DEBUG=true
      - PLAYWRIGHT_HEADLESS=true
    # Increase shared memory to reduce Chromium crashes
    shm_size: "1gb"
    # If you later add a DB, add depends_on here

