version: '3.8'

services:
  api:
    image: scrapper-backend:latest
    container_name: scrapper-api-prod
    ports:
      - '5001:5001'
    env_file:
      - .env
    environment:
      - DEBUG=false
      - PLAYWRIGHT_HEADLESS=true
    # In production we do not mount the source tree
    restart: unless-stopped
    shm_size: '1gb'
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
