"""empty message

Revision ID: 0bf4eb396743
Revises: 
Create Date: 2025-09-24 09:31:01.460165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf4eb396743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_url', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('lastmod', sa.Date(), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_url', 'origin', name='uq_hotel_url_origin')
    )
    with op.batch_alter_table('hotel_listings', schema=None) as batch_op:
        batch_op.create_index('ix_hotel_listings_hotel_url_location', ['hotel_url', 'location'], unique=False)
        batch_op.create_index('ix_hotel_listings_location', ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_listings', schema=None) as batch_op:
        batch_op.drop_index('ix_hotel_listings_location')
        batch_op.drop_index('ix_hotel_listings_hotel_url_location')

    op.drop_table('hotel_listings')
    # ### end Alembic commands ###
