"""empty message

Revision ID: fb95a476a50e
Revises: 
Create Date: 2025-09-24 08:50:41.318358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb95a476a50e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_url', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('lastmod', sa.Date(), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone='Asia/Manila'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone='Asia/Manila'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_listings')
    # ### end Alembic commands ###
